AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  observer:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 30
      Tracing: "Active"
      MemorySize: 3008
      Handler: mba.Api::handleRequest
      Runtime: java11
      CodeUri: target/minusine-bramos-akis.jar
      Policies:
        - AWSLambdaExecute
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /observe
            Method: post

  observerLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${observer}
      RetentionInDays: 1
