name: AWS Stack Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Cache maven deps
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - name: AWS cli install action
      uses: chrislennon/action-aws-cli@v1
      
    - name: Prepare java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install clojure tools-deps
      uses: DeLaGuardo/setup-clojure@master
      with:
        tools-deps: 1.10.1.469
          
    - name: Build the uberjar and deploy to AWS
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION}}
      run: |
        rm -rf classes
        mkdir classes
        ./compile.clj
        clojure -A:uberjar --target target/minusine-bramos-akis.jar
        aws cloudformation package \
        --template-file stack.yml \
        --s3-bucket mba-labs \
        --s3-prefix mba \
        --output-template-file /tmp/mba-stack.yml
         
        aws cloudformation deploy \
        --template-file /tmp/mba-stack.yml \
        --stack-name minusine-bramos-akis-dev \
        --capabilities CAPABILITY_IAM \
        --no-fail-on-empty-changeset
